# -*- coding: utf-8 -*-
username = 'guest'
email = 'guest@example.org'
password = 'passw0rd'
username2 = 'guest2'
email2 = 'guest2@example.org'
password2 = 'passw2rd'
url = 'http://dummy.example.org'
title = 'dummy title'
description = 'This description is dummy sentense.'
category0 = 'test 0'
category1 = 'テスト 0'
category2 = 'test 1 abc'
tag0 = 'test 0'
tag1 = 'テスト 0'
tag2 = 'test 1 abc'
